// Comprehensive SEO Keywords for Egyptian Nightclubs
// Format: Club Data with bilingual (Arabic & English) keywords for optimal search engine visibility

export const nightclubSEOKeywords = {
  // 1. AOWTAR CLUB (أوتار كلوب) - العجوزه فندقي فور سيزونز
  aowtar_club: {
    name: "AOWTAR CLUB",
    arabicName: "أوتار كلوب",
    location: "العجوزة - فندق فور سيزونز - الجيزة",
    keywords: [
      // English Keywords
      "AOWTAR Club Cairo",
      "AOWTAR Nightclub Giza",
      "Book AOWTAR Club",
      "AOWTAR VIP Booking",
      "AOWTAR Lounge Four Seasons",
      "Dancing Cairo AOWTAR",
      "DJ Club AOWTAR Giza",
      "AOWTAR Club Prices",
      "Fine Dining AOWTAR Club",
      "AOWTAR Club Reservation",
      "Live Music AOWTAR Cairo",
      "VIP Table Booking AOWTAR",
      "AOWTAR Club Events Cairo",
      "Nightlife Giza AOWTAR",
      "Premium Club AOWTAR Elgouza",
      "AOWTAR Club Weekend",
      "Entertainment AOWTAR Club",
      "AOWTAR Giza Nightclub Booking",
      // Arabic Keywords
      "أوتار كلوب القاهرة",
      "احجز أوتار كلوب",
      "أوتار كلوب الجيزة",
      "أوتار كلوب الحجز",
      "أوتار كلوب فور سيزونز",
      "أوتار كلوب vip",
      "الرقص أوتار كلوب",
      "ديي أوتار كلوب",
      "أسعار أوتار كلوب",
      "موسيقى حية أوتار كلوب",
      "حفلات أوتار كلوب",
      "العجوزة كلوب ليلي",
      "فندقي فور سيزونز كلوب الجيزة",
    ]
  },

  // 2. FOX CLUB (فوكس كلوب) - الجيزة - العجوزة
  fox_club: {
    name: "FOX CLUB",
    arabicName: "فوكس كلوب",
    location: "الجيزة - العجوزة",
    keywords: [
      // English Keywords
      "FOX Club Giza",
      "FOX Nightclub Cairo",
      "Book FOX Club Elgouza",
      "FOX Club VIP Tables",
      "Dancing FOX Club Giza",
      "DJ FOX Club Cairo",
      "FOX Club Booking Online",
      "FOX Club Prices",
      "Live Entertainment FOX Club",
      "Music FOX Club Giza",
      "FOX Club Reservation",
      "Premium FOX Club Cairo",
      "Weekend FOX Club",
      "FOX Lounge Cairo",
      "VIP Service FOX Club",
      "Nightlife Giza FOX",
      "FOX Club Events",
      "Entertainment Guide FOX Club",
      // Arabic Keywords
      "فوكس كلوب الجيزة",
      "احجز فوكس كلوب",
      "فوكس كلوب العجوزة",
      "فوكس كلوب الحجز",
      "فوكس كلوب vip",
      "فوكس كلوب الرقص",
      "ديي فوكس كلوب",
      "أسعار فوكس كلوب",
      "حفلات فوكس كلوب",
      "موسيقى فوكس كلوب",
      "العجوزة فوكس كلوب الليل",
      "تذاكر فوكس كلوب",
    ]
  },

  // 3. EL MALUONAERR CLUB (المليونير كلوب) - القاهرة - الزمالك
  el_millioneer_club: {
    name: "EL MILLIONEER CLUB",
    arabicName: "المليونير كلوب",
    location: "الزمالك - القاهرة",
    keywords: [
      // English Keywords
      "El Millioneer Club Cairo",
      "El Millioneer Nightclub Zamalek",
      "Book El Millioneer Club",
      "El Millioneer VIP Booking",
      "Premium Club Zamalek Cairo",
      "El Millioneer DJ Club",
      "Dancing Cairo El Millioneer",
      "El Millioneer Club Prices",
      "Luxury Nightclub Cairo",
      "El Millioneer Reservation",
      "Live Music Zamalek",
      "VIP Table Cairo El Millioneer",
      "El Millioneer Club Events",
      "Nile View Club Cairo",
      "El Millioneer Weekend",
      "High-End Club Cairo",
      "Exclusive Club Zamalek",
      "Entertainment Cairo El Millioneer",
      // Arabic Keywords
      "المليونير كلوب الزمالك",
      "احجز المليونير كلوب",
      "المليونير كلوب القاهرة",
      "المليونير كلوب الحجز",
      "المليونير كلوب vip",
      "المليونير كلوب الرقص",
      "ديي المليونير كلوب",
      "أسعار المليونير كلوب",
      "حفلات المليونير كلوب",
      "موسيقى المليونير كلوب",
      "الزمالك كلوب ليلي",
      "كلوب فاخر الزمالك",
      "حفلات الزمالك الليلية",
    ]
  },

  // 4. NOX CLUB - القاهرة - العجوزه
  nox_club: {
    name: "NOX CLUB",
    arabicName: "نوكس كلوب",
    location: "العجوزة - القاهرة",
    keywords: [
      // English Keywords
      "NOX Club Cairo",
      "NOX Nightclub Elgouza",
      "Book NOX Club",
      "NOX Club VIP",
      "NOX Club DJ",
      "Dancing NOX Club Cairo",
      "NOX Club Booking",
      "NOX Club Prices",
      "Entertainment NOX Club",
      "Music NOX Club",
      "NOX Club Reservation",
      "Premium Club Elgouza",
      "Weekend NOX Club",
      "Live Music NOX Cairo",
      "NOX Club Events",
      "VIP Table NOX",
      "Nightlife Elgouza NOX",
      "Cairo Club NOX Booking",
      // Arabic Keywords
      "نوكس كلوب القاهرة",
      "احجز نوكس كلوب",
      "نوكس كلوب العجوزة",
      "نوكس كلوب الحجز",
      "نوكس كلوب vip",
      "نوكس كلوب الرقص",
      "ديي نوكس كلوب",
      "أسعار نوكس كلوب",
      "حفلات نوكس كلوب",
      "موسيقى نوكس كلوب",
      "العجوزة كلوب ليلي",
      "تذاكر نوكس كلوب",
    ]
  },

  // 5. Stage Cairo Club - خلف النادي الأهلي
  stage_cairo_club: {
    name: "Stage Cairo Club",
    arabicName: "ستيج كايرو كلوب",
    location: "خلف النادي الأهلي - القاهرة",
    keywords: [
      // English Keywords
      "Stage Cairo Club",
      "Stage Club Ahly",
      "Book Stage Cairo",
      "Stage Club VIP Booking",
      "DJ Stage Cairo",
      "Dancing Stage Club Cairo",
      "Stage Club Prices",
      "Live Performance Stage Cairo",
      "Music Events Stage Club",
      "Stage Cairo Reservation",
      "Entertainment Stage Club",
      "Weekend Stage Cairo",
      "Premium Club Cairo Stage",
      "Stage Club Events Cairo",
      "VIP Table Stage Club",
      "Nightclub Behind Ahly",
      "Stage Cairo Nightlife",
      "Concert Venue Cairo Stage",
      // Arabic Keywords
      "ستيج كايرو كلوب",
      "احجز ستيج كايرو",
      "ستيج كلوب خلف الأهلي",
      "ستيج كلوب الحجز",
      "ستيج كلوب vip",
      "موسيقى ستيج كايرو",
      "ديي ستيج كلوب",
      "أسعار ستيج كلوب",
      "حفلات ستيج كلوب",
      "الرقص ستيج كايرو",
      "أداء حي ستيج كلوب",
      "حفلات القاهرة ستيج",
      "النادي الأهلي كلوب",
    ]
  },

  // 6. Cash Cairo - المهندسين
  cash_cairo: {
    name: "Cash Cairo",
    arabicName: "كاش كايرو",
    location: "المهندسين - الجيزة",
    keywords: [
      // English Keywords
      "Cash Cairo Club",
      "Cash Cairo Nightclub",
      "Book Cash Cairo",
      "Cash Cairo VIP",
      "DJ Cash Cairo",
      "Dancing Cash Cairo",
      "Cash Club Mohandessin",
      "Cash Cairo Booking",
      "Cash Cairo Prices",
      "Entertainment Cash Cairo",
      "Music Cash Club",
      "Cash Cairo Reservation",
      "Nightlife Mohandessin",
      "Premium Club Mohandessin",
      "Cash Cairo Events",
      "Weekend Cash Cairo",
      "VIP Table Cash Club",
      "Live Music Cash Cairo",
      // Arabic Keywords
      "كاش كايرو كلوب",
      "احجز كاش كايرو",
      "كاش كلوب المهندسين",
      "كاش كلوب الحجز",
      "كاش كلوب vip",
      "كاش كلوب الرقص",
      "ديي كاش كايرو",
      "أسعار كاش كلوب",
      "حفلات كاش كايرو",
      "موسيقى كاش كلوب",
      "المهندسين كلوب ليلي",
      "تذاكر كاش كايرو",
    ]
  },

  // 7. Omni Club Cairo - طريق نادي الجزيرة
  omni_club_cairo: {
    name: "Omni Club Cairo",
    arabicName: "أومني كلوب كايرو",
    location: "طريق نادي الجزيرة - القاهرة",
    keywords: [
      // English Keywords
      "Omni Club Cairo",
      "Omni Nightclub Egypt",
      "Book Omni Club",
      "Omni Club VIP Booking",
      "DJ Omni Club Cairo",
      "Dancing Omni Club",
      "Omni Club Island Road",
      "Omni Cairo Prices",
      "Entertainment Omni Club",
      "Music Omni Cairo",
      "Omni Club Reservation",
      "Premium Club Cairo",
      "Omni Club Events",
      "Nightlife Island Road Cairo",
      "Weekend Omni Club",
      "VIP Table Omni",
      "Live Music Omni Cairo",
      "Omni Club Booking Online",
      // Arabic Keywords
      "أومني كلوب القاهرة",
      "احجز أومني كلوب",
      "أومني كلوب الجزيرة",
      "أومني كلوب الحجز",
      "أومني كلوب vip",
      "أومني كلوب الرقص",
      "ديي أومني كلوب",
      "أسعار أومني كلوب",
      "حفلات أومني كلوب",
      "موسيقى أومني كايرو",
      "طريق نادي الجزيرة كلوب",
      "تذاكر أومني",
    ]
  },

  // 8. Echo Club - المعادي
  echo_club: {
    name: "Echo Club",
    arabicName: "إيكو كلوب",
    location: "المعادي - القاهرة",
    keywords: [
      // English Keywords
      "Echo Club Cairo",
      "Echo Nightclub Maadi",
      "Book Echo Club",
      "Echo Club VIP",
      "DJ Echo Club Cairo",
      "Dancing Echo Club",
      "Echo Club Maadi",
      "Echo Cairo Prices",
      "Entertainment Echo Club",
      "Music Echo Cairo",
      "Echo Club Reservation",
      "Nightlife Maadi Cairo",
      "Echo Club Events",
      "Weekend Echo Club",
      "VIP Table Echo",
      "Live Music Echo Cairo",
      "Premium Club Maadi",
      "Echo Club Booking Online",
      // Arabic Keywords
      "إيكو كلوب القاهرة",
      "احجز إيكو كلوب",
      "إيكو كلوب المعادي",
      "إيكو كلوب الحجز",
      "إيكو كلوب vip",
      "إيكو كلوب الرقص",
      "ديي إيكو كلوب",
      "أسعار إيكو كلوب",
      "حفلات إيكو كلوب",
      "موسيقى إيكو كايرو",
      "المعادي كلوب ليلي",
      "تذاكر إيكو كلوب",
    ]
  },

  // 9. King Club - البحر الأعظم الجيزة
  king_club: {
    name: "King Club",
    arabicName: "كينج كلوب",
    location: "البحر الأعظم - الجيزة",
    keywords: [
      // English Keywords
      "King Club Giza",
      "King Nightclub Cairo",
      "Book King Club",
      "King Club VIP Booking",
      "DJ King Club",
      "Dancing King Club Cairo",
      "King Club Ocean Road",
      "King Cairo Prices",
      "Entertainment King Club",
      "Music King Club",
      "King Club Reservation",
      "Nightlife Giza",
      "King Club Events",
      "Premium Club Giza",
      "Weekend King Club",
      "VIP Table King",
      "Live Music King Cairo",
      "King Club Booking Online",
      // Arabic Keywords
      "كينج كلوب الجيزة",
      "احجز كينج كلوب",
      "كينج كلوب البحر الأعظم",
      "كينج كلوب الحجز",
      "كينج كلوب vip",
      "كينج كلوب الرقص",
      "ديي كينج كلوب",
      "أسعار كينج كلوب",
      "حفلات كينج كلوب",
      "موسيقى كينج كايرو",
      "البحر الأعظم كلوب",
      "تذاكر كينج كلوب",
    ]
  },

  // 10. Cosmo Lounge & Club - الزمالك
  cosmo_lounge: {
    name: "Cosmo Lounge & Club",
    arabicName: "كوزمو لاونج كلوب",
    location: "الزمالك - القاهرة",
    keywords: [
      // English Keywords
      "Cosmo Lounge Cairo",
      "Cosmo Club Zamalek",
      "Book Cosmo Lounge",
      "Cosmo Club VIP Booking",
      "DJ Cosmo Club Cairo",
      "Dancing Cosmo Club",
      "Cosmo Lounge Zamalek",
      "Cosmo Cairo Prices",
      "Entertainment Cosmo Lounge",
      "Music Cosmo Club",
      "Cosmo Club Reservation",
      "Nightlife Zamalek",
      "Cosmo Club Events",
      "Premium Lounge Cairo",
      "Weekend Cosmo Club",
      "VIP Table Cosmo",
      "Live Music Cosmo Cairo",
      "Exclusive Lounge Zamalek",
      // Arabic Keywords
      "كوزمو لاونج القاهرة",
      "احجز كوزمو كلوب",
      "كوزمو كلوب الزمالك",
      "كوزمو كلوب الحجز",
      "كوزمو كلوب vip",
      "كوزمو كلوب الرقص",
      "ديي كوزمو لاونج",
      "أسعار كوزمو كلوب",
      "حفلات كوزمو كايرو",
      "موسيقى كوزمو لاونج",
      "الزمالك لاونج ليلي",
      "تذاكر كوزمو كلوب",
    ]
  },

  // 11. OVID Club - ممشى أهل مصر على النيل
  ovid_club: {
    name: "OVID Club",
    arabicName: "أوفيد كلوب",
    location: "ممشى أهل مصر - النيل - القاهرة",
    keywords: [
      // English Keywords
      "OVID Club Cairo",
      "OVID Nile Club",
      "Book OVID Club",
      "OVID Club VIP Booking",
      "DJ OVID Club",
      "Dancing OVID Club Cairo",
      "OVID Club Nile Promenade",
      "OVID Cairo Prices",
      "Entertainment OVID Club",
      "Music OVID Cairo",
      "OVID Club Reservation",
      "Nile Nightlife Cairo",
      "OVID Club Events",
      "Premium Club Nile",
      "Weekend OVID Club",
      "VIP Table OVID",
      "Live Music OVID Cairo",
      "Waterfront Club Cairo",
      // Arabic Keywords
      "أوفيد كلوب القاهرة",
      "احجز أوفيد كلوب",
      "أوفيد كلوب النيل",
      "أوفيد كلوب الحجز",
      "أوفيد كلوب vip",
      "أوفيد كلوب الرقص",
      "ديي أوفيد كلوب",
      "أسعار أوفيد كلوب",
      "حفلات أوفيد كلوب",
      "موسيقى أوفيد كايرو",
      "ممشى أهل مصر كلوب",
      "النيل كلوب ليلي",
    ]
  },

  // 12. ROVI Club - كورنيش المعادي
  rovi_club: {
    name: "ROVI Club",
    arabicName: "روفي كلوب",
    location: "كورنيش المعادي - القاهرة",
    keywords: [
      // English Keywords
      "ROVI Club Cairo",
      "ROVI Club Maadi",
      "Book ROVI Club",
      "ROVI Club VIP Booking",
      "DJ ROVI Club",
      "Dancing ROVI Club Cairo",
      "ROVI Club Maadi Corniche",
      "ROVI Cairo Prices",
      "Entertainment ROVI Club",
      "Music ROVI Cairo",
      "ROVI Club Reservation",
      "Nile Waterfront Club",
      "ROVI Club Events",
      "Premium Club Maadi",
      "Weekend ROVI Club",
      "VIP Table ROVI",
      "Live Music ROVI Cairo",
      "Corniche Nightclub Cairo",
      // Arabic Keywords
      "روفي كلوب القاهرة",
      "احجز روفي كلوب",
      "روفي كلوب المعادي",
      "روفي كلوب الحجز",
      "روفي كلوب vip",
      "روفي كلوب الرقص",
      "ديي روفي كلوب",
      "أسعار روفي كلوب",
      "حفلات روفي كلوب",
      "موسيقى روفي كايرو",
      "كورنيش المعادي كلوب",
      "تذاكر روفي كلوب",
    ]
  },

  // 13. Rai Club Nile Dragon Boat - كورنيش النيل
  rai_club_nile_dragon: {
    name: "Rai Club Nile Dragon Boat",
    arabicName: "راي كلوب النيل",
    location: "كورنيش النيل - القاهرة",
    keywords: [
      // English Keywords
      "Rai Club Cairo",
      "Nile Dragon Boat Club",
      "Book Rai Club",
      "Rai Club VIP Booking",
      "DJ Rai Club Cairo",
      "Dancing Rai Club",
      "Rai Club Nile Waterfront",
      "Rai Cairo Prices",
      "Entertainment Rai Club",
      "Music Rai Cairo",
      "Rai Club Reservation",
      "Floating Club Cairo",
      "Rai Club Events",
      "Premium Nile Club",
      "Weekend Rai Club",
      "VIP Table Rai",
      "Live Music Rai Cairo",
      "Boat Club Cairo",
      // Arabic Keywords
      "راي كلوب القاهرة",
      "احجز راي كلوب",
      "راي كلوب النيل",
      "راي كلوب الحجز",
      "راي كلوب vip",
      "راي كلوب الرقص",
      "ديي راي كلوب",
      "أسعار راي كلوب",
      "حفلات راي كلوب",
      "موسيقى راي كايرو",
      "كورنيش النيل كلوب",
      "قارب التنين كلوب",
    ]
  },

  // 14. Volt Lounge - الدقي / العجوزة
  volt_lounge: {
    name: "Volt Lounge",
    arabicName: "فولت لاونج",
    location: "الدقي / العجوزة - الجيزة",
    keywords: [
      // English Keywords
      "Volt Lounge Cairo",
      "Volt Club Giza",
      "Book Volt Lounge",
      "Volt Club VIP Booking",
      "DJ Volt Lounge",
      "Dancing Volt Club",
      "Volt Lounge Dokki",
      "Volt Club Elgouza",
      "Volt Cairo Prices",
      "Entertainment Volt Lounge",
      "Music Volt Cairo",
      "Volt Club Reservation",
      "Nightlife Dokki Giza",
      "Volt Club Events",
      "Premium Lounge Giza",
      "Weekend Volt Club",
      "VIP Table Volt",
      "Live Music Volt Cairo",
      // Arabic Keywords
      "فولت لاونج القاهرة",
      "احجز فولت لاونج",
      "فولت كلوب الدقي",
      "فولت كلوب العجوزة",
      "فولت لاونج الحجز",
      "فولت كلوب vip",
      "فولت كلوب الرقص",
      "ديي فولت لاونج",
      "أسعار فولت كلوب",
      "حفلات فولت كايرو",
      "موسيقى فولت لاونج",
      "الدقي لاونج ليلي",
    ]
  },
};

// Export common SEO keyword categories
export const seoKeywordCategories = {
  bookingPhrases: [
    "احجز الآن",
    "الحجز الآن",
    "تحفظ مقعد",
    "حجز طاولة vip",
    "احجز طاولتك",
    "اطلب تذكرة",
    "حجز حفلة",
    "Book Now",
    "Reserve a Table",
    "VIP Table Booking",
    "Online Reservation",
    "Secure Booking",
  ],
  entertainmentTypes: [
    "ديي",
    "دي جي",
    "موسيقى مباشرة",
    "الرقص",
    "حفلات",
    "عروض حية",
    "كاريوكي",
    "DJ Music",
    "Live Performances",
    "Dancing Floor",
    "Live Bands",
    "Entertainment Shows",
  ],
  vipServices: [
    "VIP Tables",
    "طاولة vip",
    "خدمة vip",
    "مقاعد vip",
    "منطقة vip",
    "VIP Lounge",
    "Exclusive Club",
    "Premium Service",
    "VIP Mixed Drinks",
    "Private Booth",
  ],
  egyptianRegions: [
    "Cairo",
    "Giza",
    "Zamalek",
    "Maadi",
    "Elgouza",
    "Dokki",
    "Mohandessin",
    "القاهرة",
    "الجيزة",
    "الزمالك",
    "المعادي",
    "العجوزة",
    "الدقي",
    "المهندسين",
    "النيل",
  ],
};

// Format: Array of keywords for individual club pages
export const clubKeywordsArray = (clubName: string, location: string) => [
  `${clubName} Cairo`,
  `${clubName} Nightclub`,
  `Book ${clubName}`,
  `${clubName} VIP Booking`,
  `${clubName} Cairo Reservation`,
  `${clubName} ${location}`,
  `Cairo Nightclub ${clubName}`,
  `Egyptian Nightclub ${clubName}`,
];
